### ISSUE TITLE
parsing issue

### ISSUE THREAD

**Issue by enikao** [LIonWeb-org/lioncore-java#69]
v0.0.14

Trying to unparse example below, leads to exception.

Id' like to use this in Munich, so it would be great if we could get it working.

```
Exception in thread "main" kotlin.NotImplementedError: An operation is not implemented.
        at com.strumenta.kolasu.model.lionweb.ReflectionBasedMetamodel.instantiate(lionweb.kt:136)
        at com.strumenta.kolasu.model.lionweb.ReflectionBasedMetamodel.prepareSerialization$lambda$15$lambda$14(lionweb.kt:201)
        at org.lionweb.lioncore.java.serialization.NodeInstantiator.instantiate(NodeInstantiator.java:48)
        at org.lionweb.lioncore.java.serialization.JsonSerialization.instantiateNodeFromSerialized(JsonSerialization.java:407)
        at org.lionweb.lioncore.java.serialization.JsonSerialization.lambda$unserializeNodes$9(JsonSerialization.java:352)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at org.lionweb.lioncore.java.serialization.JsonSerialization.unserializeNodes(JsonSerialization.java:350)
        at org.lionweb.lioncore.java.serialization.JsonSerialization.unserializeSerializationBlock(JsonSerialization.java:337)
        at org.lionweb.lioncore.java.serialization.JsonSerialization.unserializeToNodes(JsonSerialization.java:260)
        at org.lionweb.lioncore.java.serialization.JsonSerialization.unserializeToNodes(JsonSerialization.java:268)
        at io.lionweb.propertiesparser.PropertiesModelLoader.loadModel(PropertiesModelLoader.kt:14)
        at io.lionweb.propertiesparser.cli.CodeGenCommand.run(PropertiesParserCLIGroup.kt:109)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
        at io.lionweb.propertiesparser.cli.PropertiesParserCLI.main(PropertiesParserCLIGroup.kt:154)
```

The error message is _almost_ helpful (-:

File contents:

```json
{
  "serializationFormatVersion": "1",
  "metamodels": [],
  "nodes": [
    {
      "id": "1902329257909619430",
      "concept": {
        "metamodel": "io_lionweb_Properties",
        "version": "1",
        "key": "io_lionweb_Properties-PropertiesFile"
      },
      "properties": [],
      "children": [
        {
          "containment": {
            "metamodel": "io_lionweb_Properties",
            "version": "1",
            "key": "io_lionweb_Properties-PropertiesFile-props"
          },
          "children": [
            "1902329257909619431",
            "1902329257909619433",
            "1902329257909619435"
          ]
        }
      ],
      "references": [],
      "parent": null
    },
    {
      "id": "1902329257909619431",
      "concept": {
        "metamodel": "io_lionweb_Properties",
        "version": "1",
        "key": "io_lionweb_Properties-Property"
      },
      "properties": [
        {
          "property": {
            "metamodel": "io_lionweb_Properties",
            "version": "1",
            "key": "io_lionweb_Properties-Property-name"
          },
          "value": "a"
        }
      ],
      "children": [
        {
          "containment": {
            "metamodel": "io_lionweb_Properties",
            "version": "1",
            "key": "io_lionweb_Properties-Property-value"
          },
          "children": [
            "1902329257909619432"
          ]
        }
      ],
      "references": [],
      "parent": "1902329257909619430"
    },
    {
      "id": "1902329257909619432",
      "concept": {
        "metamodel": "io_lionweb_Properties",
        "version": "1",
        "key": "io_lionweb_Properties-IntValue"
      },
      "properties": [
        {
          "property": {
            "metamodel": "io_lionweb_Properties",
            "version": "1",
            "key": "io_lionweb_Properties-IntValue-value"
          },
          "value": "1231"
        }
      ],
      "children": [],
      "references": [],
      "parent": "1902329257909619431"
    },
    {
      "id": "1902329257909619433",
      "concept": {
        "metamodel": "io_lionweb_Properties",
        "version": "1",
        "key": "io_lionweb_Properties-Property"
      },
      "properties": [
        {
          "property": {
            "metamodel": "io_lionweb_Properties",
            "version": "1",
            "key": "io_lionweb_Properties-Property-name"
          },
          "value": "b"
        }
      ],
      "children": [
        {
          "containment": {
            "metamodel": "io_lionweb_Properties",
            "version": "1",
            "key": "io_lionweb_Properties-Property-value"
          },
          "children": [
            "1902329257909619434"
          ]
        }
      ],
      "references": [],
      "parent": "1902329257909619430"
    },
    {
      "id": "1902329257909619434",
      "concept": {
        "metamodel": "io_lionweb_Properties",
        "version": "1",
        "key": "io_lionweb_Properties-BooleanValue"
      },
      "properties": [],
      "children": [],
      "references": [],
      "parent": "1902329257909619433"
    },
    {
      "id": "1902329257909619435",
      "concept": {
        "metamodel": "io_lionweb_Properties",
        "version": "1",
        "key": "io_lionweb_Properties-Property"
      },
      "properties": [
        {
          "property": {
            "metamodel": "io_lionweb_Properties",
            "version": "1",
            "key": "io_lionweb_Properties-Property-name"
          },
          "value": "c"
        }
      ],
      "children": [
        {
          "containment": {
            "metamodel": "io_lionweb_Properties",
            "version": "1",
            "key": "io_lionweb_Properties-Property-value"
          },
          "children": [
            "1902329257909619436"
          ]
        }
      ],
      "references": [],
      "parent": "1902329257909619430"
    },
    {
      "id": "1902329257909619436",
      "concept": {
        "metamodel": "io_lionweb_Properties",
        "version": "1",
        "key": "io_lionweb_Properties-StringValue"
      },
      "properties": [
        {
          "property": {
            "metamodel": "io_lionweb_Properties",
            "version": "1",
            "key": "io_lionweb_Properties-StringValue-value"
          },
          "value": "foo"
        }
      ],
      "children": [],
      "references": [],
      "parent": "1902329257909619435"
    }
  ]
}
```

**Comment by enikao** [comment]
My hunch: It doesn't like number-only ids

**Comment by ftomassetti** [comment]
The problem here seems that there is a BooleanValue which is not specifying a value for the property "value":
```
    {
      "id": "1902329257909619434",
      "concept": {
        "metamodel": "io_lionweb_Properties",
        "version": "1",
        "key": "io_lionweb_Properties-BooleanValue"
      },
      "properties": [],
      "children": [],
      "references": [],
      "parent": "1902329257909619433"
    }
```
So we do not know which value to assign, as we do not have define default values. I would expect the property value to appear here and to be a boolean ("true" or "false")

**Comment by enikao** [comment]
Good catch! I'll look into it

**Comment by enikao** [comment]
Fixed by https://github.com/LIonWeb-org/lioncore-mps/pull/25
